version: "3.3"
services:
  db:
    container_name: inv_db
    image: library/postgres:12.3
    ports:
      - "5544:5544"
    environment:
      - POSTGRES_DB=inv
      - POSTGRES_USER=inv
      - POSTGRES_PASSWORD=inv
      - PGPORT=5544
