export default [
  {
    title: "American Summer",
    watch_date: "2017-01-01",
    production_year: 2011,
    directors: "J.B. Rogers",
  },
  {
    title: "Mad Max: Na drodze gniewu",
    watch_date: "2017-01-01",
    production_year: 2015,
    directors: "George Miller",
  },
  {
    title: "The secret life of pets",
    watch_date: "2017-01-01",
    production_year: 2016,
    directors: "Chris Renaud, Yarrow Cheney",
  },
  {
    title: "Batman: Zabójczy żart",
    watch_date: "2017-01-01",
    production_year: 2016,
    directors: "Sam Liu",
  },
  {
    title: "Linia życia",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "Niels Arden Oplev",
  },
  {
    title: "The blue umbrella",
    watch_date: "2017-01-01",
    production_year: 2013,
    directors: "Saschka Unseld",
  },
  {
    title: "Sausage Party",
    watch_date: "2017-01-01",
    production_year: 2016,
    directors: "Conrad Vernon, Greg Tiernan",
  },
  {
    title: "Bright",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "David Ayer",
  },
  {
    title: "Three Billboards Outside Ebbing, Missouri",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "Martin McDonagh",
  },
  {
    title: "Justice League",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "Zack Snyder",
  },
  {
    title: "Wonder Women",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "Patty Jenkins",
  },
  {
    title: "If a were a boy",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "Audrey Dana",
  },
  {
    title: "The truth about alcohol",
    watch_date: "2017-01-01",
    production_year: 2016,
    directors: "David Briggs",
  },
  {
    title: "Hot Girls Wanted",
    watch_date: "2017-01-01",
    production_year: 2015,
    directors: "Jill Bauer, Ronna Gradus",
  },
  {
    title: "Batman: Gotham by Gaslight",
    watch_date: "2017-01-01",
    production_year: 2018,
    directors: "Sam Liu",
  },
  {
    title: "Despicable me (2010) Jak ukraść księżyc",
    watch_date: "2017-01-01",
    production_year: 2010,
    directors: "Pierre Coffin, Chris Renaud",
  },
  {
    title: "Despicable me 2",
    watch_date: "2017-01-01",
    production_year: 2013,
    directors: "Pierre Coffin, Chris Renaud",
  },
  {
    title: "Minions",
    watch_date: "2017-01-01",
    production_year: 2015,
    directors: "Kyle Balda, Pierre Coffin",
  },
  {
    title: "Despicable me 3",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "Kyle Balda, Pierre Coffin",
  },
  {
    title: "Murder on the Orient Express",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "Kenneth Branagh",
  },
  {
    title: "Człowiek scyzoryk",
    watch_date: "2017-01-01",
    production_year: 2016,
    directors: "Dan Kwan, Daniel Scheinert",
  },
  {
    title: "Pacific Rim",
    watch_date: "2017-01-01",
    production_year: 2013,
    directors: "Guillermo del Toro",
  },
  {
    title: "Batman Ninja",
    watch_date: "2017-01-01",
    production_year: 2018,
    directors: "Junpei Mizusaki",
  },
  {
    title: "Lego DC Comics S H: The Flash",
    watch_date: "2017-01-01",
    production_year: 2018,
    directors: "Ethan Spaulding",
  },
  {
    title: "Logan: Wolverine",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "James Mangold",
  },
  {
    title: "Upiór w operze",
    watch_date: "2017-01-01",
    production_year: 2004,
    directors: "Joel Schumacher",
  },
  {
    title: "Kształt Wody",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "Guillermo del Toro",
  },
  {
    title: "Deadpool 2",
    watch_date: "2017-01-01",
    production_year: 2018,
    directors: "David Leitch",
  },
  {
    title: "Baby driver",
    watch_date: "2017-01-01",
    production_year: 2017,
    directors: "Edgar Wright",
  },
  {
    title: "Gwiezdne wojny: Część IV- Nowa nadzieja",
    watch_date: "2017-01-01",
    production_year: 1977,
    directors: "George Lucas",
  },
  {
    title: "Player One",
    watch_date: "2017-01-01",
    production_year: 2018,
    directors: "Steven Spielberg",
  },
  {
    title: "Noc oczyszczenia",
    watch_date: "2017-01-01",
    production_year: 2013,
    directors: "James DeMonaco",
  },
  {
    title: "Jurassic World: Upadłe królestwo",
    watch_date: "2017-01-01",
    production_year: 2018,
    directors: "Juan Antonio Bayona",
  },
  {
    title: "Pacific Rim: Uprising",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Steven S. DeKnight",
  },
  {
    title: "Coco",
    watch_date: "2018-01-01",
    production_year: 2017,
    directors: "Lee Unkrich",
  },
  {
    title: "7 Psychopatów",
    watch_date: "2018-01-01",
    production_year: 2012,
    directors: "Martin McDonagh",
  },
  {
    title: "Lego Batman movie",
    watch_date: "2018-01-01",
    production_year: 2017,
    directors: "Chris McKay",
  },
  {
    title: "Lego DC Comics Super Heroes: Aquaman: Rage of Atlantis",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Matt Peters",
  },
  {
    title: "Coco",
    watch_date: "2018-01-01",
    production_year: 2017,
    directors: "Lee Unkrich",
  },
  {
    title: "Green Lantern",
    watch_date: "2018-01-01",
    production_year: 2011,
    directors: "Martin Campbell",
  },
  {
    title: "xXx: Return of Xander Cage",
    watch_date: "2018-01-01",
    production_year: 2017,
    directors: "D.J. Caruso",
  },
  {
    title: "Auta 3",
    watch_date: "2018-01-01",
    production_year: 2017,
    directors: "Brian Fee",
  },
  {
    title: "Superman versus the Elite",
    watch_date: "2018-01-01",
    production_year: 2012,
    directors: "Michael Chang",
  },
  {
    title: "The Death of Superman",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Sam Liu, James Tucker",
  },
  {
    title: "Game Night",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "John Francis Daley, Jonathan Goldstein",
  },
  {
    title: "Tully",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Jason Reitman",
  },
  {
    title: "Skyscraper",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Rawson Marshall Thurber",
  },
  {
    title: "Miasto 44",
    watch_date: "2018-01-01",
    production_year: 2014,
    directors: "Jan Komas",
  },
  {
    title: "Taxi 5",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Franck Gastambide",
  },
  {
    title: "Vaiana: Skarb oceanu",
    watch_date: "2018-01-01",
    production_year: 2016,
    directors: "Ron Clements i John Musker",
  },
  {
    title: "Hotel Transylwania 3: Summer Vacation",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Genndy Tartakovski",
  },
  {
    title: "To all the boys I've loved before",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Susan Johnson",
  },
  {
    title: "Anon",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Andrew Niccol",
  },
  {
    title: "The do over",
    watch_date: "2018-01-01",
    production_year: 2016,
    directors: "Steven Brill",
  },
  {
    title: "Delhi Belly",
    watch_date: "2018-01-01",
    production_year: 2011,
    directors: "Abhinay Deo",
  },
  {
    title: "How it ends",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "David M. Rosenthal",
  },
  {
    title: "Ocean's 8",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Gary Ross",
  },
  {
    title: "Pakt z diabłem/Black mass",
    watch_date: "2018-01-01",
    production_year: 2015,
    directors: "Scott Cooper",
  },
  {
    title: "Revolt",
    watch_date: "2018-01-01",
    production_year: 2016,
    directors: "Joe Miale",
  },
  {
    title: "Venom",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Ruben Fleischer",
  },
  {
    title: "LEGO® NINJAGO: FILM",
    watch_date: "2018-01-01",
    production_year: 2017,
    directors: "Wielu",
  },
  {
    title: "Fantastyczne zwierzęta i jak je znaleźć",
    watch_date: "2018-01-01",
    production_year: 2016,
    directors: "David Yates",
  },
  {
    title: "Lego Marvel Super Heroes: Avengers Reassembled",
    watch_date: "2018-01-01",
    production_year: 2015,
    directors: "Rob Silvestri",
  },
  {
    title: "Lego: Przygoda",
    watch_date: "2018-01-01",
    production_year: 2014,
    directors: "Phil Lord, Chris Miller",
  },
  {
    title: "Johnny English: Nokaut",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "David Kerr",
  },
  {
    title: "Fantastic Beasts: The Crimes of Grindelwald",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "David Yates",
  },
  {
    title: "Aguaman",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "James Wan",
  },
  {
    title: "Spider-Man Uniwersum",
    watch_date: "2018-01-01",
    production_year: 2018,
    directors: "Peter Ramsey, Bob Persichetti, Rodney Rothman",
  },
  {
    title: "AlphaGo",
    watch_date: "2018-01-01",
    production_year: 2017,
    directors: "Greg Kohs",
  },
  {
    title: "Kingsman: Złoty Krąg",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Matthew Vaughn",
  },
  {
    title: "Bird Box",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Susanne Bier",
  },
  {
    title: "Bohaterowie Marvela: Doładowani na maksa",
    watch_date: "2019-01-01",
    production_year: 2013,
    directors: "Greg Richardson",
  },
  {
    title: "Criminal Umysł przestępcy",
    watch_date: "2019-01-01",
    production_year: 2016,
    directors: "Ariel Vromen",
  },
  {
    title: "Coś za mną chodzi/ It follows",
    watch_date: "2019-01-01",
    production_year: 2014,
    directors: "David Robert Mitchell",
  },
  {
    title: "W głowie Einsteina",
    watch_date: "2019-01-01",
    production_year: 2015,
    directors: "Nova",
  },
  {
    title: "The Secret Rules of Modern Living: Algorithms",
    watch_date: "2019-01-01",
    production_year: 2015,
    directors: "David Briggs",
  },
  {
    title: "Ralph Demolka w internecie",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Rich Moore, Phil Johnston",
  },
  {
    title: "Jestem legendą",
    watch_date: "2019-01-01",
    production_year: 2007,
    directors: "Francis Lawrence",
  },
  {
    title: "Beyond Skyline",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Liam O'Donnell",
  },
  {
    title: "Bumblebee",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Travis Knight",
  },
  {
    title: "Reign of Superman",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Sam Liu",
  },
  {
    title: "Catwomen",
    watch_date: "2019-01-01",
    production_year: 2004,
    directors: "Bob Kane, Bill Finger",
  },
  {
    title: "Liga Sprawiedliwości: Bogowie i Potwory",
    watch_date: "2019-01-01",
    production_year: 2015,
    directors: "Sam Liu",
  },
  {
    title: "Liga Sprawiedliwości vs Młodzi Tytani",
    watch_date: "2019-01-01",
    production_year: 2016,
    directors: "Sam Liu",
  },
  {
    title: "Batman Unlimited Monster Mayhem",
    watch_date: "2019-01-01",
    production_year: 2015,
    directors: "Butch Lukic",
  },
  {
    title: "Transformers 5",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Michael Bay",
  },
  {
    title: "Batman: Mroczne czasy / Batman: Bad Blood",
    watch_date: "2019-01-01",
    production_year: 2016,
    directors: "Jay Olivia",
  },
  {
    title: "Liga Sprawiedliwości: Tron Atlantydy",
    watch_date: "2019-01-01",
    production_year: 2015,
    directors: "Ethan Spaulding, Jay Olivia",
  },
  {
    title: "Batman vs Robin",
    watch_date: "2019-01-01",
    production_year: 2015,
    directors: "Jay Olivia",
  },
  {
    title: "Okja",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Joon-ho Bong",
  },
  {
    title: "Fanatyk",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Michał Tylka",
  },
  {
    title: "Fotograf z Mauthausen",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Mar Targarona",
  },
  {
    title: "Green Book",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Peter Farrelly",
  },
  {
    title: "Poradnik pozytywnego myślenia",
    watch_date: "2019-01-01",
    production_year: 2012,
    directors: "David O. Russell",
  },
  {
    title: "Blade Runner 2049",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Denis Villeneuve",
  },
  {
    title: "LEGO Przygoda 2",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Mike Michell",
  },
  {
    title: "Captain Marvel",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Anna Boden, Ryan Fleck",
  },
  {
    title: "Alita: Battle Angel",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Robert Rodriguez",
  },
  {
    title: "Dunkierka",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Christopher Nolan",
  },
  {
    title: "Hakerzy pamięci",
    watch_date: "2019-01-01",
    production_year: 2016,
    directors: "Nova",
  },
  {
    title: "Zabójcze Maszyny / Mortal Engines",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Christian Rivers",
  },
  {
    title: "Robin Hood: Początek",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Otto Bathurst",
  },
  {
    title: "Na skraju jutra",
    watch_date: "2019-01-01",
    production_year: 2014,
    directors: "Doug Liman",
  },
  {
    title: "Krzysiu, gdzie jesteś Christopher Robin",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Marc Forster",
  },
  {
    title: "Dyktator",
    watch_date: "2019-01-01",
    production_year: 2012,
    directors: "Larry Charles",
  },
  {
    title: "Asterix i Obelix: Tajemnica magicznego wywaru",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Alexandre Astier, Louis Clichy",
  },
  {
    title: "X-Men Geneza: Wolverine / X-Men Origins: Wolverine",
    watch_date: "2019-01-01",
    production_year: 2009,
    directors: "Gavin Hood",
  },
  {
    title: "Pain and gain / Sztanga i cash",
    watch_date: "2019-01-01",
    production_year: 2013,
    directors: "Michael Bay",
  },
  {
    title: "Avengers: End Game",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Joe & Anthony Russo",
  },
  {
    title: "Ex Machina",
    watch_date: "2019-01-01",
    production_year: 2015,
    directors: "Alex Garland",
  },
  {
    title: "Bękarty wojny",
    watch_date: "2019-01-01",
    production_year: 2009,
    directors: "Quantino Tarantino",
  },
  {
    title: "Berek / Tag",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Jeff Tomsic",
  },
  {
    title: "Constantine",
    watch_date: "2019-01-01",
    production_year: 2005,
    directors: "Francis Lawrence",
  },
  {
    title: "Shazam",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "David F. Sandberg",
  },
  {
    title: "John Wick",
    watch_date: "2019-01-01",
    production_year: 2014,
    directors: "Chad Stahelski",
  },
  {
    title: "JOB: Czyli ostatnia szara komórka",
    watch_date: "2019-01-01",
    production_year: 2016,
    directors: "Konrad Niewolski",
  },
  {
    title: "John Wick Chapter 2",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Chad Stahelski",
  },
  {
    title: "Pokemon: Volcanion i mechaniczny zachwyt",
    watch_date: "2019-01-01",
    production_year: 2016,
    directors: "Kunihiko Yuyama",
  },
  {
    title: "Pokemon: Wybieram cię!",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Kunihiko Yuyama",
  },
  {
    title: "John Wick chapter 3",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Chad Stahelski",
  },
  {
    title: "Pokemon: Detektyw Pikachu",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Rob Letterman",
  },
  {
    title: "X-Men: Mroczna Phoenix",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Simon Kinberg",
  },
  {
    title: "Us",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Jordan Peele",
  },
  {
    title: "Spiderman Far from home",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Jon Watts",
  },
  {
    title: "Hellboy",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Neil Marshall",
  },
  {
    title: "The Secret Life of Pets 2",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Chris Renaud",
  },
  {
    title: "Focus",
    watch_date: "2019-01-01",
    production_year: 2015,
    directors: "Glenn Ficarra, John Requa",
  },
  {
    title: "Scooby-Doo! i Batman: Odważniaki i straszaki",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Jake Castorena",
  },
  {
    title: "The Inventor: Out For Blood In Silicon Valley",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Alex Gibney",
  },
  {
    title: "Darkest Hour",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Joe Wright",
  },
  {
    title: "Pionek",
    watch_date: "2019-01-01",
    production_year: 2014,
    directors: "Edward Zwick",
  },
  {
    title: "LEGO DC: Batman - Family Matters",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Matt Peters",
  },
  {
    title: "LEGO Bohaterowie Marvela: Czarna Pantera",
    watch_date: "2019-01-01",
    production_year: 2018,
    directors: "Netflix",
  },
  {
    title: "Aladyn",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Guy Ritchie",
  },
  {
    title: "Toy story 4",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Josh Cooley",
  },
  {
    title: "Wild",
    watch_date: "2019-01-01",
    production_year: 2014,
    directors: "Jean-Marc Vallée",
  },
  {
    title: "Bill Bure: Paper Tiger",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Stand Up",
  },
  {
    title: "Joker",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Todd Phillips",
  },
  {
    title: "Sens życia wg Monty Pythona",
    watch_date: "2019-01-01",
    production_year: 1983,
    directors: "Terry Gilliam, Terry Jones",
  },
  {
    title: "Monty Python i Święty Graal",
    watch_date: "2019-01-01",
    production_year: 1975,
    directors: "Terry Gilliam, Terry Jones",
  },
  {
    title: "Śmierć nadejdzie dziś",
    watch_date: "2019-01-01",
    production_year: 2017,
    directors: "Christopher Landon",
  },
  {
    title: "Gemini Man",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Ang Lee",
  },
  {
    title: "Jak zostać królem",
    watch_date: "2019-01-01",
    production_year: 2010,
    directors: "Tom Hooper",
  },
  {
    title: "6 Underground",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Michael Bat",
  },
  {
    title: "Irlandczyk",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Martin Scorses",
  },
  {
    title: "Zombieland Double Tap",
    watch_date: "2019-01-01",
    production_year: 2019,
    directors: "Ruben Flenischer",
  },
  {
    title: "Kraina lodu 2",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Jennifer Lee, Chris Buck",
  },
  {
    title: "Code 8",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Jeff Chan",
  },
  {
    title: "Justice League vs Fatal Five",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Sam Liu",
  },
  {
    title: "Pokemon Power of us",
    watch_date: "2020-01-01",
    production_year: 2018,
    directors: "Tetsuo Yajima",
  },
  {
    title: "Szybcy i wściekli: Hobbs i Shaw",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "David Leitch",
  },
  {
    title: "Terminator: Mroczne przeznaczenie",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Tim Miller",
  },
  {
    title: "Zgon na pogrzebie",
    watch_date: "2020-01-01",
    production_year: 2007,
    directors: "Frank Oz",
  },
  {
    title: "Fight club",
    watch_date: "2020-01-01",
    production_year: 1999,
    directors: "David Fincher",
  },
  {
    title: "Dred",
    watch_date: "2020-01-01",
    production_year: 2012,
    directors: "Pete Travis",
  },
  {
    title: "How to Train Your Dragon: The Hidden World",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Dean DeBlois",
  },
  {
    title: "Jojo Rabbit",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Taika Waitti",
  },
  {
    title: "Doktor Dolittle",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Stephen Gaghan",
  },
  {
    title: "Knives out",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Rian Johnson",
  },
  {
    title: "Harley Quinn: Birds of Prey",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Cathy Yan",
  },
  {
    title: "Hudson Hawk",
    watch_date: "2020-01-01",
    production_year: 1991,
    directors: "Michael Lehmann",
  },
  {
    title: "The Lion King",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Jon Favreau",
  },
  {
    title: "Superman: Red Son",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Sam Liu",
  },
  {
    title: "Bloodshot",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Dave Wilson",
  },
  {
    title: "Wonder Women: Bloodlines",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Sam Liu",
  },
  {
    title: "Batman : Hush",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Justin Copeland",
  },
  {
    title: "Suicide Squad: Hell to Pay",
    watch_date: "2020-01-01",
    production_year: 2018,
    directors: "Sam Liu",
  },
  {
    title: "Sonic the Hedgehod",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Jeff Fowler",
  },
  {
    title: "The Shawshank Redemption",
    watch_date: "2020-01-01",
    production_year: 1994,
    directors: "Frank Darabont",
  },
  {
    title: "1917",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Sam Mendes",
  },
  {
    title: "Bad Boys for Life",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Bilall Fallah, Adil El Arbi",
  },
  {
    title: "Pitch Black",
    watch_date: "2020-01-01",
    production_year: 2000,
    directors: "David Twohy, M. David Melvin",
  },
  {
    title: "The Chronicles of Riddick",
    watch_date: "2020-01-01",
    production_year: 2004,
    directors: "David Twohy",
  },
  {
    title: "Riddick",
    watch_date: "2020-01-01",
    production_year: 2013,
    directors: "David Twohy",
  },
  {
    title: "Batman and Harley Quinn",
    watch_date: "2020-01-01",
    production_year: 2017,
    directors: "Sam Liu",
  },
  {
    title: "Teen Titans: The Judas Contract",
    watch_date: "2020-01-01",
    production_year: 2017,
    directors: "Sam Liu",
  },
  {
    title: "Justice League Dark",
    watch_date: "2020-01-01",
    production_year: 2017,
    directors: "Jay Oliva",
  },
  {
    title: "Batman: Assault on Arkham",
    watch_date: "2020-01-01",
    production_year: 2014,
    directors: "Jay Oliva, Ethan Spaulding",
  },
  {
    title: "Son of Batman",
    watch_date: "2020-01-01",
    production_year: 2014,
    directors: "Ethan Spaulding",
  },
  {
    title: "Justice League: War",
    watch_date: "2020-01-01",
    production_year: 2014,
    directors: "Jay Oliva",
  },
  {
    title: "Justice League The Flashpoint Paradax",
    watch_date: "2020-01-01",
    production_year: 2013,
    directors: "Jay Oliva",
  },
  {
    title: "Batman: The Dark Knight Return (2013) Part I and II",
    watch_date: "2020-01-01",
    production_year: 2013,
    directors: "Jay Oliva",
  },
  {
    title: "Batman: Year One",
    watch_date: "2020-01-01",
    production_year: 2011,
    directors: "Sam Liu, Lauren Montgomery",
  },
  {
    title: "Justice League: Doom",
    watch_date: "2020-01-01",
    production_year: 2012,
    directors: "Lauren Montgomery",
  },
  {
    title: "Green Lantern: Emerald Knights",
    watch_date: "2020-01-01",
    production_year: 2011,
    directors: "Lauren Montgomery, Jay Oliva",
  },
  {
    title: "All-Star Superman",
    watch_date: "2020-01-01",
    production_year: 2011,
    directors: "Sam Liu",
  },
  {
    title: "Superman/Batman: Apocalypse",
    watch_date: "2020-01-01",
    production_year: 2010,
    directors: "Lauren Montgomery",
  },
  {
    title: "Batman: Under the Red Hood",
    watch_date: "2020-01-01",
    production_year: 2010,
    directors: "Brandon Vietti",
  },
  {
    title: "Justice League Crisis on two Earth",
    watch_date: "2020-01-01",
    production_year: 2010,
    directors: "Sam Liu, Lauren Montgomery",
  },
  {
    title: "Green Lantern: First Flight",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Lauren Montgomery",
  },
  {
    title: "Wonder Woman",
    watch_date: "2020-01-01",
    production_year: 2009,
    directors: "Lauren Montgomery",
  },
  {
    title: "Parasite",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Joon-ho Bong",
  },
  {
    title: "Justice League Dark: Apokolips War",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Matt Peters / Christina Sotta",
  },
  {
    title: "Dżentelmeni",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Guy Ritchie",
  },
  {
    title: "Gwiezdne wojny: Nowa nadzieja IV",
    watch_date: "2020-01-01",
    production_year: 1977,
    directors: "George Lucas",
  },
  {
    title: "Gwiezdne wojny: Imperium kontratakuje V",
    watch_date: "2020-01-01",
    production_year: 1980,
    directors: "Irvin Kershner",
  },
  {
    title: "Gwiezdne wojny: Powrót Jedi VI",
    watch_date: "2020-01-01",
    production_year: 1983,
    directors: "Richard Marquand",
  },
  {
    title: "Gwiezdne wojny: Mroczne Widmo I",
    watch_date: "2020-01-01",
    production_year: 1999,
    directors: "George Lucas",
  },
  {
    title: "Gwiezdne wojny:Atak klonów II",
    watch_date: "2020-01-01",
    production_year: 2002,
    directors: "George Lucas",
  },
  {
    title: "Gwiezdne wojny: Zemsta Sithów III",
    watch_date: "2020-01-01",
    production_year: 2005,
    directors: "George Lucas",
  },
  {
    title: "Gwiezdne wojny: Przebudzenie mocy VII",
    watch_date: "2020-01-01",
    production_year: 2015,
    directors: "J. J Abrams",
  },
  {
    title: "Łotr 1. Gwiezdne wojny - historie",
    watch_date: "2020-01-01",
    production_year: 2016,
    directors: "Gareth Edwards",
  },
  {
    title: "Gwiezdne wojny: Ostatni Jedi VIII",
    watch_date: "2020-01-01",
    production_year: 2017,
    directors: "Rian Johnson",
  },
  {
    title: "Han Solo: Gwiezdne wojny - historie",
    watch_date: "2020-01-01",
    production_year: 2018,
    directors: "Ron Howard",
  },
  {
    title: "Gwiezdne wojny: Skywalker. Odrodzenie",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "J.J. Abrams",
  },
  {
    title: "Batman: Gotham Knight",
    watch_date: "2020-01-01",
    production_year: 2008,
    directors: "wielu",
  },
  {
    title: "Obłędny Rycerz",
    watch_date: "2020-01-01",
    production_year: 2001,
    directors: "Brian Helgeland",
  },
  {
    title: "Upgrade",
    watch_date: "2020-01-01",
    production_year: 2018,
    directors: "Leigh Whannell",
  },
  {
    title: "The Old Guards",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Gina Prince-Bythewood",
  },
  {
    title: "The Hungover Games",
    watch_date: "2020-01-01",
    production_year: 2014,
    directors: "Josh Stolberg",
  },
  {
    title: "The Cast Away",
    watch_date: "2020-01-01",
    production_year: 2000,
    directors: "Robert Zemeckis",
  },
  {
    title: "Assassin’s Creed",
    watch_date: "2020-01-01",
    production_year: 2016,
    directors: "Justin Kurzel",
  },
  {
    title: "Harry Potter i Kamień Filozoficzny",
    watch_date: "2020-01-01",
    production_year: 2001,
    directors: "Chris Columbus",
  },
  {
    title: "Harry Potter i Komnata Tajemnic",
    watch_date: "2020-01-01",
    production_year: 2002,
    directors: "Chris Columbus",
  },
  {
    title: "Harry Potter i więzień Azkabanu",
    watch_date: "2020-01-01",
    production_year: 2004,
    directors: "Alfonso Cuaron",
  },
  {
    title: "Harry Potter i Czara Ognia",
    watch_date: "2020-01-01",
    production_year: 2005,
    directors: "Mike Newell",
  },
  {
    title: "Harry Potter i Zakon Feniksa",
    watch_date: "2020-01-01",
    production_year: 2007,
    directors: "David Yates",
  },
  {
    title: "Harry Potter i Książę Półkrwi",
    watch_date: "2020-01-01",
    production_year: 2009,
    directors: "David Yates",
  },
  {
    title: "Harry Potter i Insygnia Śmierci: Część I",
    watch_date: "2020-01-01",
    production_year: 2010,
    directors: "David Yates",
  },
  {
    title: "Harry Potter i Insygnia Śmierci: Część II",
    watch_date: "2020-01-01",
    production_year: 2011,
    directors: "David Yates",
  },
  {
    title: "Phineas & Ferb Candace against the universe",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Dan Povenmire",
  },
  {
    title: "Scooby-Doo!",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Tony Cervone",
  },
  {
    title: "Mortal",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Andre Ovredal",
  },
  {
    title: "Klaus",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Sergio Pablos",
  },
  {
    title: "Freaks",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Adam Stein, Zach Lipovsky",
  },
  {
    title: "I am mother",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Grant Sputore",
  },
  {
    title: "Kobiety Mafii",
    watch_date: "2020-01-01",
    production_year: 2018,
    directors: "Patryk Vega",
  },
  {
    title: "Kobiety Mafii 2",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Patryk Vega",
  },
  {
    title: "Superman: Powrót",
    watch_date: "2020-01-01",
    production_year: 2006,
    directors: "Bryan Singer",
  },
  {
    title: "Człowiek ze stali",
    watch_date: "2020-01-01",
    production_year: 2013,
    directors: "Zack Snyder",
  },
  {
    title: "Może pora z tym skończyć",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Charlie Kaufman",
  },
  {
    title: "Fearless",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Cory Edwards",
  },
  {
    title: "Nocna przygoda",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Trish Sie",
  },
  {
    title: "Superman: Man of Tomorrow",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Chris Palmer",
  },
  {
    title: "Justice League: The new frontier",
    watch_date: "2020-01-01",
    production_year: 2008,
    directors: "Dave Bullock",
  },
  {
    title: "Superman: Unbound",
    watch_date: "2020-01-01",
    production_year: 2013,
    directors: "James Tucker",
  },
  {
    title: "Superlopez",
    watch_date: "2020-01-01",
    production_year: 2018,
    directors: "Javier Ruiz Caldera",
  },
  {
    title: "Epoka lodowcowa 4: Wędrówka kontynentów",
    watch_date: "2020-01-01",
    production_year: 2012,
    directors: "Mike Thurmeier, Steve Martino",
  },
  {
    title: "Śmierć nadejdzie dziś 2",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Christopher Landon",
  },
  {
    title: "Diabeł wcielony",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Antonio Campos",
  },
  {
    title: "Mulan",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Niki Caro",
  },
  {
    title: "Enola Holmes",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Harry Bradbeer",
  },
  {
    title: "The Dark knight rises",
    watch_date: "2020-01-01",
    production_year: 2012,
    directors: "Christopher Nolan",
  },
  {
    title: "Once upon a time in hollywood",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Quantino Tarantino",
  },
  {
    title: "Boże Ciało",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Jan Komasa",
  },
  {
    title: "Monty Python Żywot Briana",
    watch_date: "2020-01-01",
    production_year: 1979,
    directors: "Terry Jones",
  },
  {
    title: "Fullmetal Alcjemist",
    watch_date: "2020-01-01",
    production_year: 2017,
    directors: "Fumihiko Sori",
  },
  {
    title: "Doomsday",
    watch_date: "2020-01-01",
    production_year: 2008,
    directors: "Neil Marshall",
  },
  {
    title: "Sword Art online: Ordinal Scale",
    watch_date: "2020-01-01",
    production_year: 2017,
    directors: "Tomohiko Itō",
  },
  {
    title: "Wyprawa na księżyc",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Glen Keane",
  },
  {
    title: "The SpongeBob movie: Sponge on the run",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Tim Hill",
  },
  {
    title: "Ares",
    watch_date: "2020-01-01",
    production_year: 2016,
    directors: "Jean-Patrick Benes",
  },
  {
    title: "Alien Warfare / Navy seals kontra kosmici",
    watch_date: "2020-01-01",
    production_year: 2019,
    directors: "Jeremiah Jones",
  },
  {
    title: "Watchmen strażnicy",
    watch_date: "2020-01-01",
    production_year: 2009,
    directors: "Zack Snyder",
  },
  {
    title: "Tau",
    watch_date: "2020-01-01",
    production_year: 2018,
    directors: "Federico D'Alessandro",
  },
  {
    title: "LEGO DC: Shazam!: Czary mary i potwory",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Matt Peters",
  },
  {
    title: "Wyspa Róży",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Sydney Sibilia",
  },
  {
    title: "Mosul",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Matthew Michael Carnahan",
  },
  {
    title: "Noc Oczyszczenia: Anarchia",
    watch_date: "2020-01-01",
    production_year: 2014,
    directors: "James DeMonaco",
  },
  {
    title: "Chappie",
    watch_date: "2020-01-01",
    production_year: 2015,
    directors: "Neill Blomkamp",
  },
  {
    title: "Wonder Woman 1984",
    watch_date: "2020-01-01",
    production_year: 2020,
    directors: "Patty Jenkins",
  },
  {
    title: "Diabeł",
    watch_date: "2021-01-01",
    production_year: 2010,
    directors: "John Erick Dowdle",
  },
  {
    title: "Death to 2020",
    watch_date: "2021-01-01",
    production_year: 2020,
    directors: "Charlie Brooker",
  },
  {
    title: "Godzilla II: Król Potworów",
    watch_date: "2021-01-01",
    production_year: 2019,
    directors: "Michael Dougherty",
  },
  {
    title: "Godzilla",
    watch_date: "2021-01-01",
    production_year: 2014,
    directors: "Gareth Edwards",
  },
  {
    title: "Dracula: Historia Nieznana",
    watch_date: "2021-01-01",
    production_year: 2014,
    directors: "Gary Shore",
  },
  {
    title: "We Can Be Heroes",
    watch_date: "2021-01-01",
    production_year: 2020,
    directors: "Robert Rodriguez",
  },
  {
    title: "Wszyscy moi przyjaciele nie żyją",
    watch_date: "2021-01-01",
    production_year: 2020,
    directors: "Łukasz Targosz",
  },
  {
    title: "Emotki . Film",
    watch_date: "2021-01-01",
    production_year: 2017,
    directors: "Tony Leondis",
  },
  {
    title: "Split",
    watch_date: "2021-01-01",
    production_year: 2016,
    directors: "M. Night Shyamalan",
  },
  {
    title: "Matrix",
    watch_date: "2021-01-01",
    production_year: 1999,
    directors: "Lana Wachowski, Lilly Wachowski",
  },
  {
    title: "Matrix Reaktywacja",
    watch_date: "2021-01-01",
    production_year: 2003,
    directors: "Lana Wachowski, Lilly Wachowski",
  },
  {
    title: "Matrix Rewolucja",
    watch_date: "2021-01-01",
    production_year: 2003,
    directors: "Lana Wachowski, Lilly Wachowski",
  },
  {
    title: "Noc oszczyszczenia: Czas Wyboru",
    watch_date: "2021-01-01",
    production_year: 2016,
    directors: "James DeMonaco",
  },
  {
    title: "Pierwsza noc czyszczenia",
    watch_date: "2021-01-01",
    production_year: 2018,
    directors: "Gerard McMurray",
  },
  {
    title: "Batman Soul of the Dragon",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Sam Liu",
  },
  {
    title: "Krudowie 2: Nowa Era",
    watch_date: "2021-01-01",
    production_year: 2020,
    directors: "Joel Crawford",
  },
  {
    title: "47 Roninów / 47 Ronin",
    watch_date: "2021-01-01",
    production_year: 2013,
    directors: "Carl Rinsch",
  },
  {
    title: "Van Helsing",
    watch_date: "2021-01-01",
    production_year: 2003,
    directors: "Stephen Sommers",
  },
  {
    title: "Hansel & Gretel",
    watch_date: "2021-01-01",
    production_year: 2013,
    directors: "Anthony C. Ferrante",
  },
  {
    title: "Hansel and Gretel: Witch Hunters",
    watch_date: "2021-01-01",
    production_year: 2013,
    directors: "Tommy Wirkola",
  },
  {
    title: "Thunder Force",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Ben Falcone",
  },
  {
    title: "Shin seiki Evangelion gekijōban Air/Magokoro o, kimi ni",
    watch_date: "2021-01-01",
    production_year: 1997,
    directors: "Hideaki Anno, Kazuya Tsurumaki",
  },
  {
    title: "Pokémon: Mewto Strikes Back - Evolution",
    watch_date: "2021-01-01",
    production_year: 2019,
    directors: "Kunihiko Yuyama, Tetsuo Yajima, Motonori Sakakibara",
  },
  {
    title: "Zack Snyder's Justice League",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Zack Snyder",
  },
  {
    title: "Cruella",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Craig Gillespie",
  },
  {
    title: "The Suicide Squad",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "James Gunn",
  },
  {
    title: "Czarna Wdowa",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Cate Shortland",
  },
  {
    title: "The Last: Naruto the Movie",
    watch_date: "2021-01-01",
    production_year: 2014,
    directors: "Tsuneo Kobayashi",
  },
  {
    title: "Boruto: Naruto the Movie",
    watch_date: "2021-01-01",
    production_year: 2015,
    directors: "Hiroyuki Yamashita",
  },
  {
    title: "Wiedźmin: Zmora Wilka",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Han Kwang II",
  },
  {
    title: "Justice League",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Jeff Wamester",
  },
  {
    title: "Batman: The Long Halloween, Part one",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Chris Palmer",
  },
  {
    title: "Batman: The Long Halloween, Part two",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Butch Lukic",
  },
  {
    title: "Trollhunters: Rise of the Titans",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Andrew Schmidt, Johane Matte, Francisco Ruiz Velasco",
  },
  {
    title: "Blade Runner The Director's Cut",
    watch_date: "2021-01-01",
    production_year: 1997,
    directors: "Ridley Scott",
  },
  {
    title: "Afterlife of the Party",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Stephen Herek",
  },
  {
    title: "Scooby-Doo! Legend of the Phantosaur",
    watch_date: "2021-01-01",
    production_year: 2011,
    directors: "Ethan Spaulding",
  },
  {
    title: "Scooby-Doo on Zombie Island",
    watch_date: "2021-01-01",
    production_year: 1998,
    directors: "Kazumi Fukushima, Jim Stenstrum, Hiroshi Aoyama",
  },
  {
    title: "Godzilla: Planet of the Monsters",
    watch_date: "2021-01-01",
    production_year: 2017,
    directors: "Hiroyuki Seshita, Kōbun Shizuno",
  },
  {
    title: "Godzilla: City on the Edge of Battle",
    watch_date: "2021-01-01",
    production_year: 2018,
    directors: "Hiroyuki Seshita, Kōbun Shizuno",
  },
  {
    title: "Godzilla: The Planet Eater",
    watch_date: "2021-01-01",
    production_year: 2018,
    directors: "Hiroyuki Seshita, Kōbun Shizuno",
  },
  {
    title: "Ruchomy zamek Hauru",
    watch_date: "2021-01-01",
    production_year: 2004,
    directors: "Hayao Miyazaki",
  },
  {
    title: "Pocket Monsters the Movie: Coco",
    watch_date: "2021-01-01",
    production_year: 2020,
    directors: "Tetsuo Yajima",
  },
  {
    title: "Spirited Away: W Krainie Bogów",
    watch_date: "2021-01-01",
    production_year: 2001,
    directors: "Hayao Miyazaki",
  },
  {
    title: "Szopy w natarciu",
    watch_date: "2021-01-01",
    production_year: 1994,
    directors: "IIsao Takahata",
  },
  {
    title: "Venom 2: Carnage",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Andy Serkis",
  },
  {
    title: "Valerian i Miasto Tysiąca Planet",
    watch_date: "2021-01-01",
    production_year: 2017,
    directors: "Luc Besson",
  },
  {
    title: "Violet Evergarden: The Movie",
    watch_date: "2021-01-01",
    production_year: 2020,
    directors: "Taichi Ishidate",
  },
  {
    title: "EVANGELION: DEATH (TRUE)² / Revival of Evangelion",
    watch_date: "2021-01-01",
    production_year: 1998,
    directors: "Hideaki Anno, Kazuya Tsurumaki",
  },
  {
    title: "Straszny Film 4 | Scary Movie 4",
    watch_date: "2021-01-01",
    production_year: 2006,
    directors: "David Zucker",
  },
  {
    title: "Shang-Chi and the Legend of the Ten Rings",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Destin Daniel Cretton",
  },
  {
    title: "No Time to Die",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Cary Fukunaga",
  },
  {
    title: "Diuna",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Denis Villeneuve",
  },
  {
    title: "Color Out of Space",
    watch_date: "2021-01-01",
    production_year: 2019,
    directors: "Richard Stanley",
  },
  {
    title: "Spider-Man: No Way Home",
    watch_date: "2021-01-01",
    production_year: 2021,
    directors: "Jon Watts",
  },
  {
    title: "Injustice",
    watch_date: "2022-01-01",
    production_year: 2021,
    directors: "Matt Peters",
  },
  {
    title: "Eternals",
    watch_date: "2022-01-01",
    production_year: 2021,
    directors: "Chloé Zhao",
  },
  {
    title: "Matrix Zmartwychwstanie",
    watch_date: "2022-01-01",
    production_year: 2021,
    directors: "Lana Wachowski",
  },
  {
    title: "Resident Evil: Domena Zła",
    watch_date: "2022-01-01",
    production_year: 2002,
    directors: "Paul W.S. Anderson",
  },
  {
    title: "Resident Evil 2: Apokalipsa",
    watch_date: "2022-01-01",
    production_year: 2004,
    directors: "Alexander Witt",
  },
  {
    title: "Resident Evil: Zagłada",
    watch_date: "2022-01-01",
    production_year: 2007,
    directors: "Russell Mulcahy",
  },
  {
    title: "Resident Evil: Afterlife",
    watch_date: "2022-01-01",
    production_year: 2010,
    directors: "Paul W.S. Anderson",
  },
  {
    title: "Resident Evil: Retrybucja",
    watch_date: "2022-01-01",
    production_year: 2012,
    directors: "Paul W.S. Anderson",
  },
  {
    title: "Resident Evil: Ostatni rozdział",
    watch_date: "2022-01-01",
    production_year: 2016,
    directors: "Paul W.S. Anderson",
  },
  {
    title: "Resident Evil: Welcome to Racoon City",
    watch_date: "2022-01-01",
    production_year: 2021,
    directors: "Johannes Roberts",
  },
  {
    title: "The Batman",
    watch_date: "2022-01-01",
    production_year: 2022,
    directors: "Matt Reeves",
  },
  {
    title: "King’s Man: Pierwsza misja",
    watch_date: "2022-01-01",
    production_year: 2020,
    directors: "Matthew Vaughn",
  },
  {
    title: "Ksiezniczka Monooke",
    watch_date: "2022-01-01",
    production_year: 1997,
    directors: "Hayao Miyazaki",
  },
  {
    title: "Whisper Away",
    watch_date: "2022-01-01",
    production_year: 2020,
    directors: "Junichi Sato, Tomotaka Shibayama",
  },
  {
    title: "X-Men",
    watch_date: "2022-01-01",
    production_year: 2000,
    directors: "Bryan Singer",
  },
  {
    title: "X-2",
    watch_date: "2022-01-01",
    production_year: 2003,
    directors: "Bryan Singer",
  },
  {
    title: "X-Men: The Last Stand",
    watch_date: "2022-01-01",
    production_year: 2006,
    directors: "Brett Ratner",
  },
  {
    title: "X-Men Origins: Wolverine",
    watch_date: "2022-01-01",
    production_year: 2009,
    directors: "Gavin Hood",
  },
  {
    title: "X-Men: First Class",
    watch_date: "2022-01-01",
    production_year: 2011,
    directors: "Matthew Vaughn",
  },
  {
    title: "The Wolverine",
    watch_date: "2022-01-01",
    production_year: 2013,
    directors: "James Mangold",
  },
  {
    title: "X-Men: Days of Future Past",
    watch_date: "2022-01-01",
    production_year: 2014,
    directors: "Bryan Singer",
  },
  {
    title: "Deadpool",
    watch_date: "2022-01-01",
    production_year: 2016,
    directors: "Tim Miller",
  },
  {
    title: "X-Men: Apocalypse",
    watch_date: "2022-01-01",
    production_year: 2016,
    directors: "Bryan Singer",
  },
  {
    title: "Logan",
    watch_date: "2022-01-01",
    production_year: 2017,
    directors: "James Mangold",
  },
  {
    title: "Deadpool 2",
    watch_date: "2022-01-01",
    production_year: 2018,
    directors: "David Leitch",
  },
  {
    title: "Dark Phoenix",
    watch_date: "2022-01-01",
    production_year: 2019,
    directors: "Simon Kinberg",
  },
  {
    title: "The New Mutants",
    watch_date: "2022-01-01",
    production_year: 2020,
    directors: "Josh Boone",
  },
  {
    title: "Fantastic Beasts: The Secrets of Dumbledore",
    watch_date: "2022-01-01",
    production_year: 2022,
    directors: "David Yates",
  },
  {
    title: "Grave Encounters",
    watch_date: "2022-01-01",
    production_year: 2011,
    directors: "The Vicious Brothers",
  },
  {
    title: "Grave Encounters 2",
    watch_date: "2022-01-01",
    production_year: 2012,
    directors: "John Poliquin",
  },
  {
    title: "Oszust z Tindera",
    watch_date: "2022-01-01",
    production_year: 2022,
    directors: "Felicity Morris",
  },
];
